# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/protein_cutter',
                'doc_host': 'https://mtinti.github.io',
                'git_url': 'https://github.com/mtinti/protein_cutter',
                'lib_path': 'protein_cutter'},
  'syms': { 'protein_cutter.core': { 'protein_cutter.core.annotate_peptides_inplace': ( 'core.html#annotate_peptides_inplace',
                                                                                        'protein_cutter/core.py'),
                                     'protein_cutter.core.digest': ('core.html#digest', 'protein_cutter/core.py'),
                                     'protein_cutter.core.digest_to_set': ('core.html#digest_to_set', 'protein_cutter/core.py'),
                                     'protein_cutter.core.fasta_to_peptide_set': ( 'core.html#fasta_to_peptide_set',
                                                                                   'protein_cutter/core.py'),
                                     'protein_cutter.core.load_fasta': ('core.html#load_fasta', 'protein_cutter/core.py')}}}
