"""Pipeline to annotate peptides"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_annotation.ipynb.

# %% auto 0
__all__ = ['TEST_DATA', 'annotation_pipline']

# %% ../nbs/01_annotation.ipynb 3
from typing import Dict, Union
from pyteomics import parser
from pyteomics import mass
from pathlib import Path
from Bio import SeqIO
import pandas as pd
from .core import annotate_peptides_inplace
from .core import fasta_to_peptide_set

# %% ../nbs/01_annotation.ipynb 4
from pathlib import Path
import os

# Get the repository root
if 'GITHUB_WORKSPACE' in os.environ:
    # In GitHub Actions
    REPO_ROOT = Path(os.environ['GITHUB_WORKSPACE'])
else:
    # Local development - find repo root
    REPO_ROOT = Path.cwd()
    while not (REPO_ROOT / 'settings.ini').exists():
        if REPO_ROOT == REPO_ROOT.parent:
            REPO_ROOT = Path.cwd()  # Fallback
            break
        REPO_ROOT = REPO_ROOT.parent

TEST_DATA = REPO_ROOT / 'test_data'

print(f"Repo root: {REPO_ROOT}")
print(f"Test data dir: {TEST_DATA}")
print(f"Test data exists: {TEST_DATA.exists()}")

# %% ../nbs/01_annotation.ipynb 5
import shutil
def annotation_pipline():
    canonical_set = fasta_to_peptide_set(TEST_DATA / 'test_sequence.fa',
                                         mass_range = (0.0, 4000000.0),
                                         min_pep_length =5
                                        )
    print(canonical_set) 
    canonical_set.update(set(['DASGPAMTEIGEQPWGR','DVAGAVEFWTDR']))
                         
    annotate_peptides_inplace(TEST_DATA / "test_spectronaut_pep_out.tsv", canonical_set)

    spc_out = pd.read_csv(TEST_DATA / 'test_spectronaut_pep_out.tsv',sep='\t')
    print(spc_out.head())
    

    src = TEST_DATA / "test_spectronaut_pep_out.tsv.bk"
    dst = TEST_DATA / "test_spectronaut_pep_out.tsv"
    
    shutil.copy(src, dst)
    print(f"Restored {dst.name} from backup")    

annotation_pipline()    
