"""Pipeline to annotate peptides"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_annotation.ipynb.

# %% auto 0
__all__ = ['TEST_DATA', 'CONFIG_FILES', 'infile', 'fasta_dict', 'df_pep', 'df_prot', 'a', 'pai_res', 'cols', 'get_observable']

# %% ../nbs/01_annotation.ipynb 3
import matplotlib.pyplot as plt
from typing import Dict, Union
from pyteomics import parser
from tqdm.auto import tqdm
from pyteomics import mass
from pathlib import Path
from Bio import SeqIO
import pandas as pd
import polars as pl
import numpy as np

from .core import digest_to_empai_set
from .core import collapse_empai_entries
from .core import flag_proprietary_peptides_from_set
from .core import flag_proprietary_from_pg
from .core import load_peptides_from_fasta
from .core import load_fasta

# %% ../nbs/01_annotation.ipynb 4
from pathlib import Path
import os
import yaml
# Get the repository root
if 'GITHUB_WORKSPACE' in os.environ:
    # In GitHub Actions
    REPO_ROOT = Path(os.environ['GITHUB_WORKSPACE'])
else:
    # Local development - find repo root
    REPO_ROOT = Path.cwd()
    while not (REPO_ROOT / 'settings.ini').exists():
        if REPO_ROOT == REPO_ROOT.parent:
            REPO_ROOT = Path.cwd()  # Fallback
            break
        REPO_ROOT = REPO_ROOT.parent

TEST_DATA = REPO_ROOT / 'test_data'
CONFIG_FILES = REPO_ROOT / 'config_files'
print(f"Repo root: {REPO_ROOT}")
print(f"Test data dir: {TEST_DATA}")
print(f"Test data exists: {TEST_DATA.exists()}")

# %% ../nbs/01_annotation.ipynb 5
with open(CONFIG_FILES / 'config.yaml', 'r') as stream:
    config = yaml.safe_load(stream)
print(config)   

# %% ../nbs/01_annotation.ipynb 6
infile = TEST_DATA/'pipeline_test/prot.fa'
#infile = '../datasets/spectronaut_protein.fasta'
fasta_dict = load_fasta(infile)

# %% ../nbs/01_annotation.ipynb 8
def get_observable(sequence):
    observable_peptides = collapse_empai_entries(
    digest_to_empai_set(
        missed_cleavages = 0,
        enzyme = 'trypsin_full',
        mz_range=(100,4000),
        sequence=sequence
        
        )
    )
    return observable_peptides

# %% ../nbs/01_annotation.ipynb 11
#infile = "../datasets/spectronaut_peptide_report.tsv"
infile = TEST_DATA/'pipeline_test/pep_report.tsv'
df_pep  = pl.read_csv(infile,separator='\t').to_pandas()
df_pep = df_pep[df_pep['PEP.NrOfMissedCleavages']==0]
df_pep.head()

# %% ../nbs/01_annotation.ipynb 12
#infile = "../datasets/spectronaut_protein_report.tsv"
infile = TEST_DATA/'pipeline_test/prot_report.tsv'
df_prot = pl.read_csv(infile,separator='\t').to_pandas()
df_prot.head()

# %% ../nbs/01_annotation.ipynb 13
a=0
pai_res = []
for pg in tqdm(df_prot['PG.ProteinGroups']):
    prot = pg.split(';')[0]
    seq = fasta_dict[prot]
    seq = seq.replace('*','')
    observable_peptide = get_observable(seq)
    observed_peptide = set(df_pep[df_pep['PG.ProteinAccessions']==pg]['PEP.StrippedSequence'].unique())
    for temp_pep in observed_peptide:
        if 'M'+temp_pep in observable_peptide:
            observable_peptide.add(temp_pep)
            
    #print(observable_peptide)
    #print(observed_peptide)
    pai = len(observed_peptide)/float(len(observable_peptide))
    pai_res.append(pai)
    if len(observed_peptide-observable_peptide) > 0:
        print (prot)
        print (fasta_dict[prot])
        print('observed_peptide-observable_peptide')
        print(observed_peptide-observable_peptide)
        print('observable_peptide')
        print(observable_peptide)
        print('observed_peptide')
        print(observed_peptide)
        a+=1
        if a>=10:
            break
        print('---------------------------\n\n') 

# %% ../nbs/01_annotation.ipynb 14
cols = [n for n in df_prot.columns if 'PG.Quantity' in n]
df_prot['mean_intensity']=np.log10(df_prot[cols].mean(axis=1,skipna=True))
df_prot['pai']=pai_res
df_prot.plot(kind='scatter',x='mean_intensity',y='pai',alpha=1)

# %% ../nbs/01_annotation.ipynb 15
df_prot.head()
